version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=postgres
    ports:
      - "5433:5433"
    networks:
      - custom
networks:
  custom:
    driver: bridge
